#ifndef COMMON_H
#define COMMON_H

#define MAINWID_WIDTH 1200
#define MAINWID_HIGHT 600

#define LEFTWID_WIDTH 300
#define LEFTWID_COLOR_R 100
#define LEFTWID_COLOR_G 100
#define LEFTWID_COLOR_B 100

#define MIDWID_WIDTH_HIDE 0
#define MIDWID_WIDTH_SHOW 5
#define MIDWID_COLOR_R 30
#define MIDWID_COLOR_G 144
#define MIDWID_COLOR_B 255

#define RIGHTWID_COLOR_R 255
#define RIGHTWID_COLOR_G 255
#define RIGHTWID_COLOR_B 255
#endif // COMMON_H
